Description of com222
Home > TrnsfFltrsScripts > com222.m
com222
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
bkgd
noise
tem22 Use this for even n:
This function is called by:
SOURCE CODE
clear;
n=32;
n2=n*2;
orgn=1;
%
pp=0;
% gp: 201,202,203
gg1=bkgd(1,16,n);
gg2=bkgd(5,16,n);
gg=gg2+gg1;
mm=max(max(gg));
mn=0;
lvl=input('input noise level as a multiple of max intensity    ')
sdv=lvl*mm;
ns=noise(n2,n2,mn,sdv);
ngg=gg+ns;
%
gp1=201;
gp2=202;
gp3=203;
[x1,x21,x22,x23,x4]=nn2_22(ngg,n,gp1,orgn);
xx1=real(inn2_22(x1,n,gp1,orgn));
[z1,tem21,z22,tem23,tem4]=nn2_22(xx1,n,gp3,orgn);
ff1=real(inn2_22(z1,n,gp3,orgn));
ff2=real(inn2_22(z22,n,gp3,orgn));
ff3=real(inn2_22(x21,n,gp1,orgn));
%
xx22=real(inn2_22(x22,n,gp1,orgn));
[tem1,tem21,y22,tem23,y4]=nn2_22(xx22,n,gp2,orgn);
yy22=real(inn2_22(y22,n,gp2,orgn));
[z1,tem21,z22,tem23,tem4]=nn2_22(yy22,n,gp3,orgn);
ff4=real(inn2_22(z1,n,gp3,orgn));
ff5=real(inn2_22(z22,n,gp3,orgn));
yy4=real(inn2_22(y4,n,gp2,orgn));
[tem1,z21,tem22,z23,z4]=nn2_22(yy4,n,gp3,orgn);
ff6=real(inn2_22(z21,n,gp3,orgn));
ff7=real(inn2_22(z23,n,gp3,orgn));
ff8=real(inn2_22(z4,n,gp3,orgn));
ff9=real(inn2_22(x23,n,gp1,orgn));
ff10=real(inn2_22(x4,n,gp1,orgn));
%
subplot(3,4,1),imagesc(ngg)
subplot(3,4,2),imagesc(ff1)
subplot(3,4,3),imagesc(ff2)
subplot(3,4,4),imagesc(ff3)
subplot(3,4,5),imagesc(ff4)
subplot(3,4,6),imagesc(ff5)
subplot(3,4,7),imagesc(ff6)
subplot(3,4,8),imagesc(ff7)
subplot(3,4,9),imagesc(ff8)
subplot(3,4,10),imagesc(ff9)
subplot(3,4,11),imagesc(ff10)
subplot(3,4,12),imagesc(ff1+ff2+ff3+ff5)