Description of comute22
Home > TrnsfFltrsScripts > comute22.m
comute22
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
bkgd
noise
tem22 Use this for even n:
This function is called by:
SOURCE CODE
clear;
n=32;
n2=n*2;
orgn=1;
%
pp=1;
gg1=bkgd(2,8,n);
gg2=bkgd(4,8,n);
gg=gg1+gg2;
mm=max(max(gg));
sc=128/mm;
lvl=input('input noise level as a multiple of max intensity    ')
sdv=lvl*mm;
mn=0;
ns=noise(n2,n2,mn,sdv);
ngg=gg+ns;
%
gp1=11;
gp2=104;
%
figure(1)
[x1,x21,x22,x23,x4]=nn2_22(ngg,n,gp1,orgn);
ff1=real(inn2_22(x1,n,gp1,orgn));
ff2=real(inn2_22(x21,n,gp1,orgn));
xx22=real(inn2_22(x22,n,gp1,orgn));
[tem1,x22y21,tem22,tem23,x22y4]=nn2_22(xx22,n,gp2,orgn);
ff3=real(inn2_22(x22y21,n,gp2,orgn));
ff4=real(inn2_22(x22y4,n,gp2,orgn));
xx23=real(inn2_22(x23,n,gp1,orgn));
[x23y1,tem21,x23y22,tem23,tem4]=nn2_22(xx23,n,gp2,orgn);
ff5=real(inn2_22(x23y1,n,gp2,orgn));
ff6=real(inn2_22(x23y22,n,gp2,orgn));
xx4=real(inn2_22(x4,n,gp1,orgn));
[tem1,x4y21,tem22,x4y23,x4y4]=nn2_22(xx4,n,gp2,orgn);
ff7=real(inn2_22(x4y21,n,gp2,orgn));
ff8=real(inn2_22(x4y23,n,gp2,orgn));
ff9=real(inn2_22(x4y4,n,gp2,orgn));
subplot(3,4,1),imagesc(gg)
subplot(3,4,2),imagesc(ngg)
subplot(3,4,3),imagesc(ff1)
subplot(3,4,4),imagesc(ff2)
subplot(3,4,5),imagesc(ff3)
subplot(3,4,6),imagesc(ff4)
subplot(3,4,7),imagesc(ff5)
subplot(3,4,8),imagesc(ff6)
subplot(3,4,9),imagesc(ff7)
subplot(3,4,10),imagesc(ff8)
subplot(3,4,11),imagesc(ff9)
subplot(3,4,12),imagesc(ff2+ff3+ff5+ff7)