Description of dsum22
Home > TrnsfFltrsScripts > dsum22.m
dsum22
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
in2n2
n2n2
scene
This function is called by:
SOURCE CODE
clear;
ny=32;
nx=32;
orgn=1;
nn=max(nx,ny);
ff=scene(6,nn,orgn);
ff=ff(1:2*nx,1:2*ny);
gx=2;
gy=2;
%
[y1,y21,y12,y22]=n2n2(ff,nx,ny,gx,gy);
yy1=real(in2n2(y1,nx,ny,gx,gy));
yy21=real(in2n2(y21,nx,ny,gx,gy));
yy12=real(in2n2(y12,nx,ny,gx,gy));
yy22=real(in2n2(y22,nx,ny,gx,gy));