Description of e_4f_2
Home > TrnsfFltrsScripts > e_4f_2.m
e_4f_2
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
im_4n_2
m_4n_2
noise
This function is called by:
SOURCE CODE
clear;
m=16;
n=16;
m2=m+m;
m4=m2+m2;
n2=n+n;
gg(1:m4,1:n2)=zeros(m4,n2);
xr=floor((m4-2)*rand);
yr=floor((n2-n/2)*rand);
gg(xr+1:xr+2,1+yr:n/2+yr)=ones(2,n/2);
mn=1;
sdv=0;
ns=noise(m4,n2,mn,sdv);
ngg=gg+ns;
[y1,y21,y22,y41,y42,y8]=m_4n_2(ngg);
yy1=real(im_4n_2(y1));
yy21=real(im_4n_2(y21));
yy22=real(im_4n_2(y22));
yy41=real(im_4n_2(y41));
yy42=real(im_4n_2(y42));
yy8=real(im_4n_2(y8));
subplot(2,4,1),imagesc(gg)
subplot(2,4,2),imagesc(ngg)
subplot(2,4,3),imagesc(yy1)
subplot(2,4,4),imagesc(yy21)
subplot(2,4,5),imagesc(yy22)
subplot(2,4,6),imagesc(yy41)
subplot(2,4,7),imagesc(yy42)
subplot(2,4,8),imagesc(yy8)
m(1)=max(max(ngg));
m(2)=max(max(yy1));
m(3)=max(max(yy21));
m(4)=max(max(yy22));
m(5)=max(max(yy41));
m(6)=max(max(yy42));
m(7)=max(max(yy8));
m'