Description of even2
Home > TrnsfFltrsScripts > even2.m
even2
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
cn_2 Semidirect product convolution of 1-dimensional signals.
in_2 Inverse semidirect product transform.
n_2 Semidirect product transform.
This function is called by:
SOURCE CODE
clear;
n=8;
n2=n*2;
m=n/2;
orgn=0;
%
xx=rand(n2,1);
uu=rand(n2,1);
[y1,y2]=n_2(xx,n);
z=zeros(n2,1);
z(3,1)=y2(3,1);
z(3+n,1)=y2(3+n,1);
%
zz=in_2(z,n);
yy2=in_2(y2,n);
%
uz=cn_2(uu,zz);
[u1,u2]=n_2(uz,n);
%