Description of ft2
Home > TrnsfFltrsScripts > ft2.m
ft2
PURPOSE
SYNOPSIS
function y=ft2(x,d2);
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
dgn22 Degenerate 2 X 2
idgn_22 Degenerate 2 X 2
imm2_22 Use this for even n:
in2n2
n2n2
nn2_4 n must be a multiple of 4
nn_4_alt0 n must be a multiple of 4
SOURCE CODE
function y=ft2(x,d2);
rt2=1/(sqrt(2));
for nn=1:d2
   y(1,nn)=rt2*(x(1,nn)+x(2,nn));
   y(2,nn)=rt2*(x(1,nn)-x(2,nn));
end