Description of ft4
Home > TrnsfFltrsScripts > ft4.m
ft4
PURPOSE
SYNOPSIS
function y=ft4(x,d1);
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
dgn22 Degenerate 2 X 2
idgn_22 Degenerate 2 X 2
imm2_22 Use this for even n:
SOURCE CODE
function y=ft4(x,d1);
for nn=1:d1
   t1=x(1,nn)+x(3,nn);
   t2=x(1,nn)-x(3,nn);
   t3=x(2,nn)+x(4,nn);
   t4=x(2,nn)-x(4,nn);
   y(1,nn)=.5*(t1+t3);
   y(2,nn)=.5*(t2+t4);
   y(3,nn)=.5*(t1-t3);
   y(4,nn)=.5*(t2-t4);
end