Description of noise
Home > TrnsfFltrsScripts > noise.m
noise
PURPOSE
SYNOPSIS
function y=noise(bk,bm,mn,sdv);
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
box
com222
comute22
e_4f_2
ee2
ee4
ee6
ee_2
ee_22_2
ee_22_alt0
ee_4
ee_4_2
flt1
fnd
fnd8
other22
pat5
prog8
rain
slp
trns
SOURCE CODE
function y=noise(bk,bm,mn,sdv);
for k1=1:bk
   for k2=1:bm
      x1=rand;
      x2=rand;
      y(k1,k2)=mn+sdv*sqrt(-2.0*log(x1))*cos(2.0);
   end
end