Description of rain
Home > TrnsfFltrsScripts > rain.m
rain
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
inn_22 Use this for even n:
nn_22 Use this for even n:
noise
This function is called by:
SOURCE CODE
clear;
n=48;
n2=n*2;
orgn=1;
%
pp=0;
% gp: 11, 13, 14, 23, 29, 31,201
W=imread('c:\windows\desktop\data\projects\sttr\pictures\wine1.tif');
gg(1:n2,1:n2,1:3)=W(4:n2+3,4:n2+3,1:3);
gg=double(gg);
mm=max(max(gg));
sc=128/mm;
mn=0;
sdv=0;
ns=noise(n2,n2,mn,sdv);
%ngg=gg+ns;
%
%pg=imread('fx1.tif');
%spg=pg(1341:1596,1157:1412);
%spg=double(spg);
%
%gp2=104;
%[y1,y21,y22,y23,y4]=mm2_22(spg,n,gp2);
%yy1=real(imm2_22(y1,n,gp2));
%yy21=real(imm2_22(y21,n,gp2));
%yy22=real(imm2_22(y22,n,gp2));
%yy23=real(imm2_22(y23,n,gp2));
%yy4=real(imm2_22(y4,n,gp2));
%
[11 12 13 14 15 18 19 23 29 31]
[103 104 201 202 203]
gp1=input('input the group number    ')
[x1,x21,x22,x23,x4]=nn_22(gg(:,:,1),gp1);
xx1(:,:,1)=real(inn_22(x1,gp1));
xx21(:,:,1)=real(inn_22(x21,gp1));
xx22(:,:,1)=real(inn_22(x22,gp1));
xx23(:,:,1)=real(inn_22(x23,gp1));
xx4(:,:,1)=real(inn_22(x4,gp1));
figure(1)
subplot(3,2,1),imagesc(gg(:,:,1))
subplot(3,2,2),imagesc(xx1(:,:,1))
subplot(3,2,3),imagesc(xx21(:,:,1))
subplot(3,2,4),imagesc(xx22(:,:,1))
subplot(3,2,5),imagesc(xx23(:,:,1))
subplot(3,2,6),imagesc(xx4(:,:,1))
%
[x1,x21,x22,x23,x4]=nn_22(gg(:,:,2),gp1);
xx1(:,:,2)=real(inn_22(x1,gp1));
xx21(:,:,2)=real(inn_22(x21,gp1));
xx22(:,:,2)=real(inn_22(x22,gp1));
xx23(:,:,2)=real(inn_22(x23,gp1));
xx4(:,:,2)=real(inn_22(x4,gp1));
figure(2)
subplot(3,2,1),imagesc(gg(:,:,2))
subplot(3,2,2),imagesc(xx1(:,:,2))
subplot(3,2,3),imagesc(xx21(:,:,2))
subplot(3,2,4),imagesc(xx22(:,:,2))
subplot(3,2,5),imagesc(xx23(:,:,2))
subplot(3,2,6),imagesc(xx4(:,:,2))
%
[x1,x21,x22,x23,x4]=nn_22(gg(:,:,3),gp1);
xx1(:,:,3)=real(inn_22(x1,gp1));
xx21(:,:,3)=real(inn_22(x21,gp1));
xx22(:,:,3)=real(inn_22(x22,gp1));
xx23(:,:,3)=real(inn_22(x23,gp1));
xx4(:,:,3)=real(inn_22(x4,gp1));
figure(3)
subplot(3,2,1),imagesc(gg(:,:,3))
subplot(3,2,2),imagesc(xx1(:,:,3))
subplot(3,2,3),imagesc(xx21(:,:,3))
subplot(3,2,4),imagesc(xx22(:,:,3))
subplot(3,2,5),imagesc(xx23(:,:,3))
subplot(3,2,6),imagesc(xx4(:,:,3))
%
figure(4)
subplot(3,2,1),image(gg/256)
cx1=xx1+abs(min(min(min(xx1))));
cx1=cx1/max(max(max(cx1)));
subplot(3,2,2),image(cx1)
cx21=xx21+abs(min(min(min(xx21))));
cx21=cx21/max(max(max(cx21)));
subplot(3,2,3),image(cx21)
cx22=xx22+abs(min(min(min(xx22))));
cx22=cx22/max(max(max(cx22)));
subplot(3,2,4),image(cx22)
cx23=xx23+abs(min(min(min(xx23))));
cx23=cx23/max(max(max(cx23)));
subplot(3,2,5),image(cx23)
cx4=xx4+abs(min(min(min(xx4))));
cx4=cx4/max(max(max(cx4)));
subplot(3,2,6),image(cx4)